//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G_ShopDomain.Entities
{
    using Itenso.TimePeriod;
    using System;
    using System.Collections.Generic;

    public partial class CaThe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaThe()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public int MaCaThe { get; set; }
        public int MaLoai { get; set; }
        public string TenCaThe { get; set; }
        public string MoTa { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public Nullable<int> GiaMua { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> KhuyenMai { get; set; }
        public string TinhTrang { get; set; }
        public string HinhAnh { get; set; }
        public string Video { get; set; }
    
        public virtual Loai Loai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
    }
    
}
